### ISSUE TITLE
Minor: When an WIM (Image) has multiple index

### ISSUE THREAD

**Issue by stgrdk** [SCConfigMgr/ConfigMgr#5] opened 2017-10-17 19:05 UTC
In Invoke-CMApplyDriverPackage.ps1 

I came across a customer who wanted to use your tool but had trouble finding OS Architecture
Line 327 # Determine OS Image architecture for running task sequence from web service
I figured it was because the WIM file in the OS step had 2 index, and the TS referred to index 2.
When I removed the Index 1 the script worked and resultet in value 9.

Perhaps a check for index?

It looks kinda like this:
![1](https://user-images.githubusercontent.com/4374469/31684015-db3eb66e-b37e-11e7-8025-d560a19ab2da.png)

**Comment by NickolajA** [comment] 2017-10-17 19:16
Yeah, it's a known bug. It will be addressed in ConfigMgr WebService version 1.5.0.

**Closed** 2017-10-17 19:17 UTC

**Comment by Wolfereign** [comment] 2019-01-17 23:38
I've noticed this exact behavior with WebService version 1.7.0 and Script version 2.1.5.  Using a Windows 10 1803 wim with ~6 different indexes.  Once I removed all but one indexes then it worked as intended.
