### ISSUE TITLE
Invoke-CMApplyDriverPackage.ps1 does not work on Dell a Dell E6430

### ISSUE THREAD

**Issue by StephanHeyer** [SCConfigMgr/ConfigMgr#13] opened 2018-01-17 18:06 UTC
Hi,
when running Invoke-CMApplyDriverPackage.ps1 (version 2.0.0 and 1.1.8 tested) on a Dell E6430, none of the packages are recognized as compatible. ("Package does not meet computer model,..."). Therefore the script errors out. The same task sequence works fine on E7450 or E7470 systems. 
[ApplyDriverPackage.log](https://github.com/SCConfigMgr/ConfigMgr/files/1640108/ApplyDriverPackage.log)

Thank you for looking into this.

Kind regards
Stephan Heyer
Zehnder GmbH

**Comment by viriio** [comment] 2018-01-18 10:58
Hi Stephan, 

I'm just a random on here trying to get this working I have a separate issue. Thought I might try help.

I believe the issue is on line 467

It currently set to:
$ComputerDetectionMethod = "^$($ComputerModel)$"

You could try change to:
$ComputerDetectionMethod = "$ComputerModel"

Basically how I read is its try to set SystemSKU but because it can't be found it would fall back to the computer model. In your case the computer model is found but the outputted string is:
^Latitude E6430$ so it would match everything else but the computer model.

Goodluck

Grant

**Comment by NickolajA** [comment] 2018-01-18 11:15
Hi Stephan,

Could you try with version 2.0.1 that was just committed. Like viriio wrote, there was a bug in the detection method when falling back to computer model. Regex was put in the wrong variable.

**Comment by StephanHeyer** [comment] 2018-01-18 13:12
Hi Nickolaj,

I can only see version 2.0.0 from 6 days ago.

![18-01-_2018_14-08-05](https://user-images.githubusercontent.com/15195011/35099760-7bdc860a-fc59-11e7-8983-657eb49723fc.png)

**Comment by StephanHeyer** [comment] 2018-01-19 07:32
Hi, have now downloaded 2.0.1 and tried it. It exits with an syntax error.
[smsts.log](https://github.com/SCConfigMgr/ConfigMgr/files/1645628/smsts.log)

**Comment by NBL-HEIM** [comment] 2018-01-23 23:22
@viriio @NickolajA 

Hello guys, 

I was wondering if I can pick your guys brain on this script.  I too am also trying to dissect how all this works and the area that i'm stumbling on is the $SystemSKU and how its applied to download driver packages.  Where in the process does it somehow apply, say a Dell XPS 13 9360 with a SystemSKU of 075B know to download the package from the distribution point? The only area where i see SystemSKU references is in the Driver Package comments section: 

Dell XPS 13 9360 Windows 10 x64 Drivers (Models included:075B)

This is the stuff thats written automatically in the comments section of the driver package when you use the driver automation tool to make a driver package.  Is this where it detects and use the $SystemSKU variable? 

Much thanks and excellent work on the tool so far!

**Comment by StephanHeyer** [comment] 2018-01-25 10:31
Hi, with version 2.0.2 of the script, it works on Dell Latitude xx30/40/50/70/80 series perfectly. Thank you for your quick support!

**Comment by NBL-HEIM** [comment] 2018-01-25 14:42
Downloaded the new 2.0.2 of this script.  also downloaded maurice's latest 5.1.8 DAT tool.  I completely blew out the Dell XPS Notebook 9360 from my test configmgr environment.  Redownloaded the package from the new 5.1.8 DAT tool and it packaged it as "Drivers - Dell XPS Notebook 9360 - Windows 10 x64"  

Still wouldn't apply the drivers. 

i'm concerned that at the beginning of the ApplyDriverPackage.log it states that the model i'm imaging is "XPS 13 9360"  Maybe there is a mismatch on the detected model name and how this driver pack is downloaded and packaged with the DAT tool.

If I rename the package "Drivers - Dell XPS Notebook 9360 - Windows 10 x64" to Drivers - XPS 13 9360 - Windows 10 x64" .....would this satisfy that model detection criteria and work from there?

Thanks everyone

**Comment by NickolajA** [comment] 2018-01-29 21:35
This should be fixed in 2.0.4 of the Invoke-CMApplyDriverPackage.ps1 script.

**Closed by NickolajA** 2018-01-29 21:35 UTC
